### PR TITLE
Issue #24: addJavascriptInterface security fix

### LINKED ISSUE #24: addJavascriptInterface security check
Verify we're not vulnerable to `WebView.addJavascriptInterface` [reflection exploits](http://developer.android.com/reference/android/webkit/WebView.html#addJavascriptInterface%28java.lang.Object,%20java.lang.String%29) on `API<17`.
- [x] Check loading post data from .org sites with raw JavaScript in the content
- [x] Check previewing (should not render any JS in the post being previewed)

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #24.
- On `API<17`, replaced the `nativeCallbackHandler` `JavascriptInterface` with running JS callbacks through a sandboxed iframe, which are received by `WebViewClient.shouldOverrideUrlLoading` and piped through to the `JsCallbackReceiver`
- Dropped `NativeStateJsInterface` for all APIs. Instead, the native API level and localized Strings are injected when loading the `android-editor.html` file
- Added profiling markers to track editor startup time

### CODE REVIEW

File: WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java [hunk 1]
```diff
@@ -372,14 +374,26 @@ protected void initJsEditor() {
...
+                    "nativeState.localizedStringUploadingGallery = '" + getString(R.string.uploading_gallery_placeholder) + "';\n");
         }
 
-        mWebView.addJavascriptInterface(new JsCallbackReceiver(this), JS_CALLBACK_HANDLER);
-        mWebView.addJavascriptInterface(new NativeStateJsInterface(getActivity().getApplicationContext()),
-                                        JS_STATE_INTERFACE);
+        // To avoid reflection security issues with JavascriptInterface on API<17, we use an iframe to make URL requests
+        // for callbacks from JS instead. These are received by WebViewClient.shouldOverrideUrlLoading() and then
+        // passed on to the JsCallbackReceiver
+        if (Build.VERSION.SDK_INT < 17) {
```
Comment (maxme) [inline WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java:392]: I hope custom ROMs are not messing with these version codes, but in case they do, we should maybe use `Build.VERSION_CODES.JELLY_BEAN_MR1` instead of `17`.

Comment (maxme) [inline WordPressEditor/src/main/java/org/wordpress/android/editor/EditorFragment.java:392]: scratch that - we can't reference `Build.VERSION_CODES` on the JS side

**Comment by maxme** [comment]
:shipit:
