### PR TITLE
Issue #394: Undefined removedNode.attributes in onMutationObserved

### LINKED ISSUE #394: Crash report 5.4: Cannot call method 'getNamedItem' of undefined
```
Non-fatal Exception: org.wordpress.android.JavaScriptException: Uncaught TypeError: Cannot call method 'getNamedItem' of undefined
       at JavaScriptException.(ZSSRichTextEditor.js:242)
```

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #394.

cc @maxme

### CODE REVIEW

File: libs/editor-common/assets/ZSSRichTextEditor.js [hunk 1]
```diff
@@ -235,6 +235,11 @@ ZSSEditor.onMutationObserved = function(mutations) {
     mutations.forEach(function(mutation) {
         for (var i = 0; i < mutation.removedNodes.length; i++) {
             var removedNode = mutation.removedNodes[i];
+            if (!removedNode.attributes) {
+                // Fix for https://github.com/wordpress-mobile/WordPress-Editor-Android/issues/394
+                // If removedNode doesn't have an attributes property, it's not of type Node and we shouldn't proceed
+                return;
```
Comment (maxme) [inline libs/editor-common/assets/ZSSRichTextEditor.js]: Should we `continue` to the next removed node?

Comment (aforcier) [inline libs/editor-common/assets/ZSSRichTextEditor.js]: You're right, fixed in ebf1208.

**Comment by maxme** [comment]
:shipit:
